version: '3.8'

services:
  app:
    build:
      context: .
      args:
        JAR_FILE: OCR_Receipt-0.0.1-SNAPSHOT.jar
    container_name: ocr-app
    ports:
      - "8080:8080"
    environment:
      user: "alex"